# Generated by Django 2.2 on 2020-05-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20180730_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='edition',
        ),
    ]
