# Generated by Django 2.2 on 2020-05-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_remove_publication_edition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('-id',), 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AddField(
            model_name='publication',
            name='promoted',
            field=models.BooleanField(default=False, verbose_name='Promocionar'),
        ),
    ]
